@host=http://127.0.0.1:3000/api
@userId=63999b19f2fff88e12b3cbd1
@accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSm9obkRvZSIsImVtYWlsIjoiYTFAYi5jb20iLCJpZCI6IjYzOTk5YjE5ZjJmZmY4OGUxMmIzY2JkMSIsImlhdCI6MTY3MTAxMzMyNCwiZXhwIjoxNjcxMDE2OTI0fQ.YvLJEDMzmC7c-VH23XCy9iNyjeJYBWX-M4CxYTqern8



############################ AUTH ############################

POST {{host}}/auth/register
Content-Type: application/json

{
    "email": "a1@b.com",
    "firstName": "John",
    "lastName": "Doe",
    "password": "Abcd1234!"
}

###

POST {{host}}/auth/login
Content-Type: application/json

{
    "email": "a1@b.com",
    "password": "Abcd1234!"
}


############################ USER ############################

GET {{host}}/users/{{userId}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}

###

PUT {{host}}/users/{{userId}}/profile
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "firstName": "John1",
    "lastName": "Doe1"
}


############################ FILE ASSET ############################

GET {{host}}/file-assets

###

POST {{host}}/file-assets/delete-by-url
Content-Type: application/json

{
    "url": "https://mak-dev-test.s3.eu-central-1.amazonaws.com/nestjs-prisma-starter/dn2l16_c86.png"
}