@host=http://127.0.0.1:3000/api
@userId=63999b19f2fff88e12b3cbd1
@accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSm9objFEb2UxIiwiZW1haWwiOiJhMUBiLmNvbSIsImlkIjoiNjM5OTliMTlmMmZmZjg4ZTEyYjNjYmQxIiwiaWF0IjoxNjcxMDc0MjczLCJleHAiOjE2NzEwNzc4NzN9.aSCpUxfc_5acb2tOst8So3G7ns38ZDOeg8XLcy5bEUc



############################ AUTH ############################

POST {{host}}/auth/register
Content-Type: application/json

{
    "email": "a1@b.com",
    "firstName": "John",
    "lastName": "Doe",
    "password": "Abcd1234!"
}

###

POST {{host}}/auth/login
Content-Type: application/json

{
    "email": "a1@b.com",
    "password": "Abcd1234!"
}


############################ USER ############################

GET {{host}}/users/{{userId}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}

###

PUT {{host}}/users/{{userId}}/profile
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "firstName": "John1",
    "lastName": "Doe1"
}


############################ FILE ASSET ############################

GET {{host}}/file-assets?page=1&size=3

###

GET {{host}}/file-assets/bucket-content

###

POST {{host}}/file-assets/delete-by-url
Content-Type: application/json

{
    "url": "https://mak-dev-test.s3.eu-central-1.amazonaws.com/nestjs-prisma-starter/dn2l16_c86.png"
}